config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items do
    member do
      patch :complete
    end
  end
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @items = Item.where(:user_id => current_user.id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @item = current_user.items.build 
  end

  def create
    @item = current_user.items.build(items_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update(items_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def complete
    @item = Item.find(params[:id])
    if @item.completed_at?
      @item.update(completed_at: nil)
    else
      @item.update(completed_at: Time.now)
    end
    redirect_to root_path
  end

  private

  def items_params
    params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <div class="flex flex-col mb-4">
    <%= f.input :title, label: "Item",
        label_html: { class: "mb-2 uppercase font-bold text-lg text-white m-3"}, 
        input_html: { class: "block border py-2 px-3 text-gray-sarkest w-80 m-3" } %>
  </div>
  <div class="flex flex-col mb-4">
    <%= f.input :description, 
        label_html: { class: "mb-2 uppercase font-bold text-lg text-white m-3"}, 
        input_html: { class: "block border py-2 px-3 text-grey-darkest overflow-auto h-32 w-80 m-3" } %>
  </div>
  <div class="flex">
    <%= f.button :submit, class: "bg-gray-400 hover:bg-gray-500 text-white uppercase text-lg mx-auto p-4 rounded m-3" %>
    <%= link_to "Cancel", root_path, class: "bg-red-400 hover:bg-red-500 text-white uppercase text-lg mx-auto p-4 rounded m-3" %>
  </div>
<% end %>

app/views/items/_welcome_page.html.erb
<div class="py-20" style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%)">
  <div class="container mx-auto px-6">
    <h2 class="text-4xl font-bold mb-2 text-white">
      Smart todo with Hiptime!
    </h2>
    <h3 class="text-2xl mb-8 text-gray-200">
      Monitor your productivity any time for free!!.
    </h3>

    <%= link_to "Sign Up Now!", new_user_registration_path, class: "bg-white font-bold rounded-full py-4 px-8 shadow-lg uppercase tracking-wider"%> 
  </div>
</div>

app/views/items/edit.html.erb
<div class="container mx-auto">
  <div class="flex justify-center pt-6">
    <div class="flex flex-col justify-center bg-gray-600 rounded">
      <div class="flex justify-center">
        <h1 class="text-white uppercase text-lg">Edit Todo Item</h1>
      </div>

      <div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <div class="container mx-auto pt-4 bg-gray-700 rounded-lg shadow mt-2 mb-2">
      <div class="container mx-auto p-4">
        <div class="bg-gray-200 p-2 rounded-lg">
          <h2 class="text-blue-300 text-2xl"><%= link_to item.title, item %></h2>
        </div>
        <div class="p-2">
          <p class="text-white"><%= item.description %></p>
        </div>
      <% if item.completed? %>
        <div class="p-2">
          <%= link_to complete_item_path(item), method: :patch do %>
            <svg class="w-10 inline-block bg-green-300 hover:bg-green-600 text-green-600 hover:text-green-300 cursor-pointer" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
            </svg>
            <span class="text-green-300 hover:text-green-400 uppercase mouse">Completed</span>
          <% end %>
        </div>
      <% else %>
        <div class="p-2">
          <%= link_to complete_item_path(item), method: :patch do %>
            <svg class="w-10 inline-block bg-red-300 hover:bg-red-600 text-red-600 hover:text-red-300 cursor-pointer" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
            <span class="text-red-300 hover:text-red-400 uppercase mouse">Not Completed</span>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>
  <div class="container mx-auto pt-4">
    <%= link_to "New Item", new_item_path, class: "bg-gray-400 uppercase hover:bg-gray-500 text-white text-md p-4 rounded" %>
  </div>
<% else %>  
  <%= render 'welcome_page'%>
<% end %>

app/views/items/new.html.erb
<div class="flex justify-center pt-6">
  <div class="flex flex-col justify-center bg-gray-600 rounded">
    <div class="flex justify-center">
      <h1 class="text-white uppercase text-lg">New Todo Item</h1>
    </div>

    <div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container mx-auto pt-4 bg-gray-700 rounded-lg shadow h-60">
  <div class="flex flex-col justify-left item-left m-4">
    <div class="text-left">
      <h2 class="text-white text-4xl"><%= @item.title %></h2>
      <h2 class="text-blue-400 text-lg">Created by: <%= @item.user.email %></h2>
      <p class="text-white"><%= @item.description %></p>
    </div>
    <div class="block pt-4">
      <%= link_to "Back", root_path, class: "bg-gray-400 uppercase hover:bg-gray-500 text-white text-md p-4 rounded" %>
      <%= link_to "Edit", edit_item_path(@item), class: "bg-blue-400 uppercase hover:bg-blue-500 text-white text-md p-4 rounded" %>
      <%= link_to "Delete", item_path(@item), method: :delete, data: {confirm: "Are you sure?"}, class: "bg-red-400 uppercase hover:bg-red-500 text-white text-md p-4 rounded" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiptime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-gray-600 bg-blue-50">
  
    <nav class="bg-gray-700 shadow-lg">
      <div class="container mx-auto">
        <div class="sm:flex justify-between">
          <%= link_to "hiptime", root_path,  class: "text-white text-2xl font-bold p-3 uppercase" %>
          <ul class="text-gray-400 sm:self-center text-xl border-t sm:border-none">
            <% if user_signed_in? %>
              <li class="sm:inline-block">
                <%= link_to "Create Item", new_item_path, class: "p-3 hover:text-white" %>
              </li>
            <% end %>
            <% if current_user.present?%>
              <li class="sm:inline-block">
                <%= link_to "Sing Out", destroy_user_session_path, method: :delete, class: "p-3 hover:text-white" %>
              </li>
            <% else %>
              <li class="sm:inline-block">
                <%= link_to "Log In", new_user_session_path, class: "p-3 hover:text-white" %>
              </li>
              <li class="sm:inline-block">
                <%= link_to "Sing Up", new_user_registration_path, class: "p-3 hover:text-white" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
  </nav>
  <div class="container mx-auto">
    <p class="notice text-green-700 py-3 rounded relative sfont-bold"><%= notice %></p>
    <p class="alert text-red-700 py-3 rounded relative sfont-bold"><%= alert %></p>
  </div>
    <%= yield %>
  </body>
</html>